name: "Chromatic"
on: pull_request
jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true

      - name: Extract Storybook URL
        id: extract_url
        run: echo "::set-output name=storybookUrl::$(echo $(cat chromatic-output.log | grep -o 'https://.*\.chromatic\.com'))"
        shell: bash

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🚀storybook: ${{ steps.extract_url.outputs.storybookUrl }}"